#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_HandPose

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ALI_HandPose.ALI_HandPose_C.HandPoseLayer
// 0x0020 (0x0020 - 0x0000)
struct ALI_HandPose_C_HandPoseLayer final
{
public:
	struct FPoseLink                              AnimationPose;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              HandPoseLayer_0;                                   // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ALI_HandPose_C_HandPoseLayer) == 0x000008, "Wrong alignment on ALI_HandPose_C_HandPoseLayer");
static_assert(sizeof(ALI_HandPose_C_HandPoseLayer) == 0x000020, "Wrong size on ALI_HandPose_C_HandPoseLayer");
static_assert(offsetof(ALI_HandPose_C_HandPoseLayer, AnimationPose) == 0x000000, "Member 'ALI_HandPose_C_HandPoseLayer::AnimationPose' has a wrong offset!");
static_assert(offsetof(ALI_HandPose_C_HandPoseLayer, HandPoseLayer_0) == 0x000010, "Member 'ALI_HandPose_C_HandPoseLayer::HandPoseLayer_0' has a wrong offset!");

}

