#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_TurnInPlace

#include "Basic.hpp"

#include "ALI_TurnInPlace_classes.hpp"
#include "ALI_TurnInPlace_parameters.hpp"


namespace SDK
{

// Function ALI_TurnInPlace.ALI_TurnInPlace_C.TurnInPlaceLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       TurnInPlaceLayer_0                                     (Parm, OutParm, NoDestructor)

void IALI_TurnInPlace_C::TurnInPlaceLayer(const struct FPoseLink& InPose, struct FPoseLink* TurnInPlaceLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_TurnInPlace_C", "TurnInPlaceLayer");

	Params::ALI_TurnInPlace_C_TurnInPlaceLayer Parms{};

	Parms.InPose = std::move(InPose);

	AsUObject()->ProcessEvent(Func, &Parms);

	if (TurnInPlaceLayer_0 != nullptr)
		*TurnInPlaceLayer_0 = std::move(Parms.TurnInPlaceLayer_0);
}

}

