#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_EnhancedLocomotion

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ALI_EnhancedLocomotion.ALI_EnhancedLocomotion_C
// 0x0000 (0x0000 - 0x0000)
class IALI_EnhancedLocomotion_C final
{
public:
	void EnhancedLocomotionLayer(const struct FPoseLink& InPose, struct FPoseLink* EnhancedLocomotionLayer_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALI_EnhancedLocomotion_C">();
	}
	static class IALI_EnhancedLocomotion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALI_EnhancedLocomotion_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IALI_EnhancedLocomotion_C) == 0x000001, "Wrong alignment on IALI_EnhancedLocomotion_C");
static_assert(sizeof(IALI_EnhancedLocomotion_C) == 0x000001, "Wrong size on IALI_EnhancedLocomotion_C");

}

