#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Behavior_AttackBehaviorBase

#include "Basic.hpp"

#include "Behavior_AttackBehaviorBase_classes.hpp"
#include "Behavior_AttackBehaviorBase_parameters.hpp"


namespace SDK
{

// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.AttemptCancellation
// (Public, BlueprintCallable, BlueprintEvent)

void UBehavior_AttackBehaviorBase_C::AttemptCancellation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "AttemptCancellation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.BeginHitWindow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          HitWindowEventSource                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBehavior_AttackBehaviorBase_C::BeginHitWindow(class UObject* HitWindowEventSource)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "BeginHitWindow");

	Params::Behavior_AttackBehaviorBase_C_BeginHitWindow Parms{};

	Parms.HitWindowEventSource = HitWindowEventSource;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.DrawDebugHitbox
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBehavior_AttackBehaviorBase_C::DrawDebugHitbox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "DrawDebugHitbox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.EndHitWindow
// (Public, BlueprintCallable, BlueprintEvent)

void UBehavior_AttackBehaviorBase_C::EndHitWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "EndHitWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.ExecuteUbergraph_Behavior_AttackBehaviorBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBehavior_AttackBehaviorBase_C::ExecuteUbergraph_Behavior_AttackBehaviorBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "ExecuteUbergraph_Behavior_AttackBehaviorBase");

	Params::Behavior_AttackBehaviorBase_C_ExecuteUbergraph_Behavior_AttackBehaviorBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.FindAndTrackTarget
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UVAnimNotify_ActionCameraTracking*CameraTracking_Notify                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  Tracking_Duration                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBehavior_AttackBehaviorBase_C::FindAndTrackTarget(const class UVAnimNotify_ActionCameraTracking* CameraTracking_Notify, double Tracking_Duration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "FindAndTrackTarget");

	Params::Behavior_AttackBehaviorBase_C_FindAndTrackTarget Parms{};

	Parms.CameraTracking_Notify = CameraTracking_Notify;
	Parms.Tracking_Duration = Tracking_Duration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.HandleAttackActionEvent
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Event_Tag                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UAnimNotifyActionEventInfo*       Anim_Notify_Action_Event                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBehavior_AttackBehaviorBase_C::HandleAttackActionEvent(const struct FGameplayTag& Event_Tag, class UAnimNotifyActionEventInfo* Anim_Notify_Action_Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "HandleAttackActionEvent");

	Params::Behavior_AttackBehaviorBase_C_HandleAttackActionEvent Parms{};

	Parms.Event_Tag = std::move(Event_Tag);
	Parms.Anim_Notify_Action_Event = Anim_Notify_Action_Event;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.OnEnd
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInterrupted                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBehavior_AttackBehaviorBase_C::OnEnd(bool bInterrupted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "OnEnd");

	Params::Behavior_AttackBehaviorBase_C_OnEnd Parms{};

	Parms.bInterrupted = bInterrupted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.OnInit
// (Event, Protected, BlueprintEvent)

void UBehavior_AttackBehaviorBase_C::OnInit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "OnInit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.OnUpdate
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBehavior_AttackBehaviorBase_C::OnUpdate(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "OnUpdate");

	Params::Behavior_AttackBehaviorBase_C_OnUpdate Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.RunHitDetection
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBehavior_AttackBehaviorBase_C::RunHitDetection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "RunHitDetection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.ShouldCancelToOtherAction
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   ShouldCancel                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBehavior_AttackBehaviorBase_C::ShouldCancelToOtherAction(bool* ShouldCancel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "ShouldCancelToOtherAction");

	Params::Behavior_AttackBehaviorBase_C_ShouldCancelToOtherAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ShouldCancel != nullptr)
		*ShouldCancel = Parms.ShouldCancel;
}


// Function Behavior_AttackBehaviorBase.Behavior_AttackBehaviorBase_C.SignalAttackContinuation
// (Public, BlueprintCallable, BlueprintEvent)

void UBehavior_AttackBehaviorBase_C::SignalAttackContinuation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Behavior_AttackBehaviorBase_C", "SignalAttackContinuation");

	UObject::ProcessEvent(Func, nullptr);
}

}

