#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BehaviorMap_Creature_Ghosts

#include "Basic.hpp"

#include "BehaviorMap_DefaultCreature_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BehaviorMap_Creature_Ghosts.BehaviorMap_Creature_Ghosts_C
// 0x0000 (0x0078 - 0x0078)
class UBehaviorMap_Creature_Ghosts_C final : public UBehaviorMap_DefaultCreature_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BehaviorMap_Creature_Ghosts_C">();
	}
	static class UBehaviorMap_Creature_Ghosts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBehaviorMap_Creature_Ghosts_C>();
	}
};
static_assert(alignof(UBehaviorMap_Creature_Ghosts_C) == 0x000008, "Wrong alignment on UBehaviorMap_Creature_Ghosts_C");
static_assert(sizeof(UBehaviorMap_Creature_Ghosts_C) == 0x000078, "Wrong size on UBehaviorMap_Creature_Ghosts_C");

}

