#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AltarGameMode

#include "Basic.hpp"

#include "BP_AltarGameMode_classes.hpp"
#include "BP_AltarGameMode_parameters.hpp"


namespace SDK
{

// Function BP_AltarGameMode.BP_AltarGameMode_C.ExecuteUbergraph_BP_AltarGameMode
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AltarGameMode_C::ExecuteUbergraph_BP_AltarGameMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AltarGameMode_C", "ExecuteUbergraph_BP_AltarGameMode");

	Params::BP_AltarGameMode_C_ExecuteUbergraph_BP_AltarGameMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AltarGameMode.BP_AltarGameMode_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AltarGameMode_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AltarGameMode_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

