#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_effectInvisibility

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_effectInvisibility.BP_effectInvisibility_C
// 0x0000 (0x0140 - 0x0140)
class UBP_effectInvisibility_C final : public UTESEffectShader
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_effectInvisibility_C">();
	}
	static class UBP_effectInvisibility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_effectInvisibility_C>();
	}
};
static_assert(alignof(UBP_effectInvisibility_C) == 0x000008, "Wrong alignment on UBP_effectInvisibility_C");
static_assert(sizeof(UBP_effectInvisibility_C) == 0x000140, "Wrong size on UBP_effectInvisibility_C");

}

