#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generic_BDP_StaticHelmet

#include "Basic.hpp"

#include "BP_Generic_BDP_StaticHelmet_classes.hpp"
#include "BP_Generic_BDP_StaticHelmet_parameters.hpp"


namespace SDK
{

// Function BP_Generic_BDP_StaticHelmet.BP_Generic_BDP_StaticHelmet_C.ExecuteUbergraph_BP_Generic_BDP_StaticHelmet
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Generic_BDP_StaticHelmet_C::ExecuteUbergraph_BP_Generic_BDP_StaticHelmet(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Generic_BDP_StaticHelmet_C", "ExecuteUbergraph_BP_Generic_BDP_StaticHelmet");

	Params::BP_Generic_BDP_StaticHelmet_C_ExecuteUbergraph_BP_Generic_BDP_StaticHelmet Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Generic_BDP_StaticHelmet.BP_Generic_BDP_StaticHelmet_C.OnAttachedToPhenotype
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVCharacterPhenotypeData*         PhenotypeData                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UTESRace*                         CharacterRace                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// ECharacterSex                           CharacterSex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Generic_BDP_StaticHelmet_C::OnAttachedToPhenotype(class UVCharacterPhenotypeData* PhenotypeData, class UTESRace* CharacterRace, ECharacterSex CharacterSex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Generic_BDP_StaticHelmet_C", "OnAttachedToPhenotype");

	Params::BP_Generic_BDP_StaticHelmet_C_OnAttachedToPhenotype Parms{};

	Parms.PhenotypeData = PhenotypeData;
	Parms.CharacterRace = CharacterRace;
	Parms.CharacterSex = CharacterSex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Generic_BDP_StaticHelmet.BP_Generic_BDP_StaticHelmet_C.SetGenderedStaticMeshes
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECharacterSex                           Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UStaticMesh*                      MaleVersion                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UStaticMesh*                      FemaleVersion                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Generic_BDP_StaticHelmet_C::SetGenderedStaticMeshes(ECharacterSex Selection, class UStaticMesh* MaleVersion, class UStaticMesh* FemaleVersion)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Generic_BDP_StaticHelmet_C", "SetGenderedStaticMeshes");

	Params::BP_Generic_BDP_StaticHelmet_C_SetGenderedStaticMeshes Parms{};

	Parms.Selection = Selection;
	Parms.MaleVersion = MaleVersion;
	Parms.FemaleVersion = FemaleVersion;

	UObject::ProcessEvent(Func, &Parms);
}

}

