#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generic_BDP_UB_FullArmor

#include "Basic.hpp"

#include "BP_Generic_BDP_UpperBody_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Generic_BDP_UB_FullArmor.BP_Generic_BDP_UB_FullArmor_C
// 0x0008 (0x0468 - 0x0460)
class ABP_Generic_BDP_UB_FullArmor_C final : public ABP_Generic_BDP_UpperBody_C
{
public:
	class UBPC_WeapBloodSplatter_C*               BPC_WeapBloodSplatter;                             // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Generic_BDP_UB_FullArmor_C">();
	}
	static class ABP_Generic_BDP_UB_FullArmor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Generic_BDP_UB_FullArmor_C>();
	}
};
static_assert(alignof(ABP_Generic_BDP_UB_FullArmor_C) == 0x000008, "Wrong alignment on ABP_Generic_BDP_UB_FullArmor_C");
static_assert(sizeof(ABP_Generic_BDP_UB_FullArmor_C) == 0x000468, "Wrong size on ABP_Generic_BDP_UB_FullArmor_C");
static_assert(offsetof(ABP_Generic_BDP_UB_FullArmor_C, BPC_WeapBloodSplatter) == 0x000460, "Member 'ABP_Generic_BDP_UB_FullArmor_C::BPC_WeapBloodSplatter' has a wrong offset!");

}

