#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Volumetric_GroundFog

#include "Basic.hpp"

#include "BP_Volumetric_GroundFog_classes.hpp"
#include "BP_Volumetric_GroundFog_parameters.hpp"


namespace SDK
{

// Function BP_Volumetric_GroundFog.BP_Volumetric_GroundFog_C.Setup Ground Fog Mask Paarameters
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Volumetric_GroundFog_C::Setup_Ground_Fog_Mask_Paarameters()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Volumetric_GroundFog_C", "Setup Ground Fog Mask Paarameters");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Volumetric_GroundFog.BP_Volumetric_GroundFog_C.Setup Ground Fog Material Parameters
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Volumetric_GroundFog_C::Setup_Ground_Fog_Material_Parameters()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Volumetric_GroundFog_C", "Setup Ground Fog Material Parameters");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Volumetric_GroundFog.BP_Volumetric_GroundFog_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Volumetric_GroundFog_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Volumetric_GroundFog_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

