#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeatherInterior

#include "Basic.hpp"

#include "BP_WeatherInterior_classes.hpp"
#include "BP_WeatherInterior_parameters.hpp"


namespace SDK
{

// Function BP_WeatherInterior.BP_WeatherInterior_C.ExecuteUbergraph_BP_WeatherInterior
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WeatherInterior_C::ExecuteUbergraph_BP_WeatherInterior(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WeatherInterior_C", "ExecuteUbergraph_BP_WeatherInterior");

	Params::BP_WeatherInterior_C_ExecuteUbergraph_BP_WeatherInterior Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WeatherInterior.BP_WeatherInterior_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_WeatherInterior_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WeatherInterior_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

