#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPE_ImpactMaterialType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum BPE_ImpactMaterialType.BPE_ImpactMaterialType
// NumValues: 0x0005
enum class EBPE_ImpactMaterialType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	BPE_MAX                                  = 4,
};

}

