#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: COND_CheckLastInputTimer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "COND_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass COND_CheckLastInputTimer.COND_CheckLastInputTimer_C
// 0x0010 (0x0050 - 0x0040)
class UCOND_CheckLastInputTimer_C final : public UCOND_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_COND_CheckLastInputTimer_C;         // 0x0040(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_AltarPlayerCameraManager_C*         CameraManager;                                     // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_COND_CheckLastInputTimer(int32 EntryPoint);
	void PostInit(class UVStateBase* OwnerState);
	bool CheckCondition(class UVStateBase* CurrentState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"COND_CheckLastInputTimer_C">();
	}
	static class UCOND_CheckLastInputTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCOND_CheckLastInputTimer_C>();
	}
};
static_assert(alignof(UCOND_CheckLastInputTimer_C) == 0x000008, "Wrong alignment on UCOND_CheckLastInputTimer_C");
static_assert(sizeof(UCOND_CheckLastInputTimer_C) == 0x000050, "Wrong size on UCOND_CheckLastInputTimer_C");
static_assert(offsetof(UCOND_CheckLastInputTimer_C, UberGraphFrame_COND_CheckLastInputTimer_C) == 0x000040, "Member 'UCOND_CheckLastInputTimer_C::UberGraphFrame_COND_CheckLastInputTimer_C' has a wrong offset!");
static_assert(offsetof(UCOND_CheckLastInputTimer_C, CameraManager) == 0x000048, "Member 'UCOND_CheckLastInputTimer_C::CameraManager' has a wrong offset!");

}

