#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_SpellCast_Single

#include "Basic.hpp"

#include "TABP_SpellCast_Single_classes.hpp"
#include "TABP_SpellCast_Single_parameters.hpp"


namespace SDK
{

// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UTABP_SpellCast_Single_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "AnimGraph");

	Params::TABP_SpellCast_Single_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_65EF51F4457F755020BF1DA476D23C69
// (BlueprintEvent)

void UTABP_SpellCast_Single_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_65EF51F4457F755020BF1DA476D23C69()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_65EF51F4457F755020BF1DA476D23C69");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_709473A44FC3E99319EABC8F1E1BC292
// (BlueprintEvent)

void UTABP_SpellCast_Single_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_709473A44FC3E99319EABC8F1E1BC292()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_709473A44FC3E99319EABC8F1E1BC292");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_A1F0AA6C456A532A99D0EDA528863022
// (BlueprintEvent)

void UTABP_SpellCast_Single_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_A1F0AA6C456A532A99D0EDA528863022()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_A1F0AA6C456A532A99D0EDA528863022");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_A92D6C994E7E5E62CD57E5BC865A96EE
// (BlueprintEvent)

void UTABP_SpellCast_Single_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_A92D6C994E7E5E62CD57E5BC865A96EE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_A92D6C994E7E5E62CD57E5BC865A96EE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_B0A1CCC44BC9125DE1282388601DFF1A
// (BlueprintEvent)

void UTABP_SpellCast_Single_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_B0A1CCC44BC9125DE1282388601DFF1A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_B0A1CCC44BC9125DE1282388601DFF1A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_B5C534CF4AAB05487959C3BAF2F0C3AF
// (BlueprintEvent)

void UTABP_SpellCast_Single_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_B5C534CF4AAB05487959C3BAF2F0C3AF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Single_AnimGraphNode_TransitionResult_B5C534CF4AAB05487959C3BAF2F0C3AF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.ExecuteUbergraph_TABP_SpellCast_Single
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_SpellCast_Single_C::ExecuteUbergraph_TABP_SpellCast_Single(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "ExecuteUbergraph_TABP_SpellCast_Single");

	Params::TABP_SpellCast_Single_C_ExecuteUbergraph_TABP_SpellCast_Single Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_SpellCast_Single.TABP_SpellCast_Single_C.SpellCastingLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       SpellCastingLayer_0                                    (Parm, OutParm, NoDestructor)

void UTABP_SpellCast_Single_C::SpellCastingLayer(struct FPoseLink* SpellCastingLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Single_C", "SpellCastingLayer");

	Params::TABP_SpellCast_Single_C_SpellCastingLayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SpellCastingLayer_0 != nullptr)
		*SpellCastingLayer_0 = std::move(Parms.SpellCastingLayer_0);
}

}

