#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_ConversationIdle

#include "Basic.hpp"

#include "TABP_ConversationIdle_classes.hpp"
#include "TABP_ConversationIdle_parameters.hpp"


namespace SDK
{

// Function TABP_ConversationIdle.TABP_ConversationIdle_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UTABP_ConversationIdle_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_ConversationIdle_C", "AnimGraph");

	Params::TABP_ConversationIdle_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function TABP_ConversationIdle.TABP_ConversationIdle_C.ConversationIdleLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       ConversationIdleLayer_0                                (Parm, OutParm, NoDestructor)

void UTABP_ConversationIdle_C::ConversationIdleLayer(const struct FPoseLink& InPose, struct FPoseLink* ConversationIdleLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_ConversationIdle_C", "ConversationIdleLayer");

	Params::TABP_ConversationIdle_C_ConversationIdleLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (ConversationIdleLayer_0 != nullptr)
		*ConversationIdleLayer_0 = std::move(Parms.ConversationIdleLayer_0);
}


// Function TABP_ConversationIdle.TABP_ConversationIdle_C.ExecuteUbergraph_TABP_ConversationIdle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_ConversationIdle_C::ExecuteUbergraph_TABP_ConversationIdle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_ConversationIdle_C", "ExecuteUbergraph_TABP_ConversationIdle");

	Params::TABP_ConversationIdle_C_ExecuteUbergraph_TABP_ConversationIdle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

