#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OriginalMenu_InventoryMainPart

#include "Basic.hpp"

#include "WBP_OriginalMenu_InventoryMainPart_classes.hpp"
#include "WBP_OriginalMenu_InventoryMainPart_parameters.hpp"


namespace SDK
{

// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_10_OnListViewUpdated__DelegateSignature
// (BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_10_OnListViewUpdated__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_10_OnListViewUpdated__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_11_OnListViewItemHovered__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_11_OnListViewItemHovered__DelegateSignature(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_11_OnListViewItemHovered__DelegateSignature");

	Params::WBP_OriginalMenu_InventoryMainPart_C_BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_11_OnListViewItemHovered__DelegateSignature Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_12_OnSortTypeUpdated__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EOriginalInventoryMenuSortType          SortType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_12_OnSortTypeUpdated__DelegateSignature(EOriginalInventoryMenuSortType SortType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_12_OnSortTypeUpdated__DelegateSignature");

	Params::WBP_OriginalMenu_InventoryMainPart_C_BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_12_OnSortTypeUpdated__DelegateSignature Parms{};

	Parms.SortType = SortType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_13_OnSortIsReversedUpdated__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    IsReversed                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_13_OnSortIsReversedUpdated__DelegateSignature(bool IsReversed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_13_OnSortIsReversedUpdated__DelegateSignature");

	Params::WBP_OriginalMenu_InventoryMainPart_C_BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_13_OnSortIsReversedUpdated__DelegateSignature Parms{};

	Parms.IsReversed = IsReversed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_6_OnMouseHoverListViewChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    IsHovered_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_6_OnMouseHoverListViewChanged__DelegateSignature(bool IsHovered_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_6_OnMouseHoverListViewChanged__DelegateSignature");

	Params::WBP_OriginalMenu_InventoryMainPart_C_BndEvt__WBP_OriginalMenu_InventoryMainPart_inv_mainContent_K2Node_ComponentBoundEvent_6_OnMouseHoverListViewChanged__DelegateSignature Parms{};

	Parms.IsHovered_0 = IsHovered_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_ModernMenu_ContainerInventory_MainContent_K2Node_ComponentBoundEvent_9_OnListViewItemClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_ModernMenu_ContainerInventory_MainContent_K2Node_ComponentBoundEvent_9_OnListViewItemClicked__DelegateSignature(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_ModernMenu_ContainerInventory_MainContent_K2Node_ComponentBoundEvent_9_OnListViewItemClicked__DelegateSignature");

	Params::WBP_OriginalMenu_InventoryMainPart_C_BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_ModernMenu_ContainerInventory_MainContent_K2Node_ComponentBoundEvent_9_OnListViewItemClicked__DelegateSignature Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_0_OnTab1Clicked__DelegateSignature
// (BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_0_OnTab1Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_0_OnTab1Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_1_OnTab2Clicked__DelegateSignature
// (BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_1_OnTab2Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_1_OnTab2Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_2_OnTab3Clicked__DelegateSignature
// (BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_2_OnTab3Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_2_OnTab3Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_3_OnTab4Clicked__DelegateSignature
// (BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_3_OnTab4Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_3_OnTab4Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_4_OnTab5Clicked__DelegateSignature
// (BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_4_OnTab5Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BndEvt__WBP_OriginalMenu_InventoryMainPart_WBP_Original_Tabs_K2Node_ComponentBoundEvent_4_OnTab5Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.ChangePage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELegacyInventoryMenuPage                NewPage                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::ChangePage(ELegacyInventoryMenuPage NewPage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "ChangePage");

	Params::WBP_OriginalMenu_InventoryMainPart_C_ChangePage Parms{};

	Parms.NewPage = NewPage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.DropAllItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::DropAllItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "DropAllItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.DropItem
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::DropItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "DropItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.ExecuteUbergraph_WBP_OriginalMenu_InventoryMainPart
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::ExecuteUbergraph_WBP_OriginalMenu_InventoryMainPart(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "ExecuteUbergraph_WBP_OriginalMenu_InventoryMainPart");

	Params::WBP_OriginalMenu_InventoryMainPart_C_ExecuteUbergraph_WBP_OriginalMenu_InventoryMainPart Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.FocusListFirstItem
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::FocusListFirstItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "FocusListFirstItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.Get Item List View
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWBP_OriginalMenu_InventoryListView_C**NewParam                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::Get_Item_List_View(class UWBP_OriginalMenu_InventoryListView_C** NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "Get Item List View");

	Params::WBP_OriginalMenu_InventoryMainPart_C_Get_Item_List_View Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.GetDisabledFilterEnumsForGivenPage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELegacyInventoryMenuPage                Page                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<EOriginalInventoryMenuSortType>* DisabledFilterEnums                                    (Parm, OutParm)

void UWBP_OriginalMenu_InventoryMainPart_C::GetDisabledFilterEnumsForGivenPage(ELegacyInventoryMenuPage Page, TArray<EOriginalInventoryMenuSortType>* DisabledFilterEnums)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "GetDisabledFilterEnumsForGivenPage");

	Params::WBP_OriginalMenu_InventoryMainPart_C_GetDisabledFilterEnumsForGivenPage Parms{};

	Parms.Page = Page;

	UObject::ProcessEvent(Func, &Parms);

	if (DisabledFilterEnums != nullptr)
		*DisabledFilterEnums = std::move(Parms.DisabledFilterEnums);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.GetFilter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWBP_OriginalMenu_Inventory_Filter_C**Filter                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::GetFilter(class UWBP_OriginalMenu_Inventory_Filter_C** Filter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "GetFilter");

	Params::WBP_OriginalMenu_InventoryMainPart_C_GetFilter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Filter != nullptr)
		*Filter = Parms.Filter;
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.GetIsFilterFocused
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   IsFilterFocused                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::GetIsFilterFocused(bool* IsFilterFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "GetIsFilterFocused");

	Params::WBP_OriginalMenu_InventoryMainPart_C_GetIsFilterFocused Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsFilterFocused != nullptr)
		*IsFilterFocused = Parms.IsFilterFocused;
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.OnFocus
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::OnFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "OnFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.OnInteractWithItem
// (BlueprintCallable, BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::OnInteractWithItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "OnInteractWithItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.OnItemClicked
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::OnItemClicked(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "OnItemClicked");

	Params::WBP_OriginalMenu_InventoryMainPart_C_OnItemClicked Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.OnSortIsReversedUpdated
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsReversed                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::OnSortIsReversedUpdated(bool IsReversed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "OnSortIsReversedUpdated");

	Params::WBP_OriginalMenu_InventoryMainPart_C_OnSortIsReversedUpdated Parms{};

	Parms.IsReversed = IsReversed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.OnSortTypeUpdated
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EOriginalInventoryMenuSortType          SortType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::OnSortTypeUpdated(EOriginalInventoryMenuSortType SortType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "OnSortTypeUpdated");

	Params::WBP_OriginalMenu_InventoryMainPart_C_OnSortTypeUpdated Parms{};

	Parms.SortType = SortType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.SetPageTitle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELegacyInventoryMenuPage                Page                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::SetPageTitle(ELegacyInventoryMenuPage Page)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "SetPageTitle");

	Params::WBP_OriginalMenu_InventoryMainPart_C_SetPageTitle Parms{};

	Parms.Page = Page;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.SetSelectedTab
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELegacyInventoryMenuPage                Page                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::SetSelectedTab(ELegacyInventoryMenuPage Page)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "SetSelectedTab");

	Params::WBP_OriginalMenu_InventoryMainPart_C_SetSelectedTab Parms{};

	Parms.Page = Page;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.ToggleSorting
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_OriginalMenu_InventoryMainPart_C::ToggleSorting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "ToggleSorting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.Update Fatigue Bar Value
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::Update_Fatigue_Bar_Value(double NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "Update Fatigue Bar Value");

	Params::WBP_OriginalMenu_InventoryMainPart_C_Update_Fatigue_Bar_Value Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.Update Health Bar Value
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::Update_Health_Bar_Value(double NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "Update Health Bar Value");

	Params::WBP_OriginalMenu_InventoryMainPart_C_Update_Health_Bar_Value Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.Update Magicka Bar Value
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::Update_Magicka_Bar_Value(double NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "Update Magicka Bar Value");

	Params::WBP_OriginalMenu_InventoryMainPart_C_Update_Magicka_Bar_Value Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.UpdateCurrentPage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ELegacyInventoryMenuPage                Page                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainPart_C::UpdateCurrentPage(ELegacyInventoryMenuPage Page)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "UpdateCurrentPage");

	Params::WBP_OriginalMenu_InventoryMainPart_C_UpdateCurrentPage Parms{};

	Parms.Page = Page;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.UpdateListViewItems
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FOriginalInventoryMenuItemProperties>&Items                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_OriginalMenu_InventoryMainPart_C::UpdateListViewItems(const TArray<struct FOriginalInventoryMenuItemProperties>& Items)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "UpdateListViewItems");

	Params::WBP_OriginalMenu_InventoryMainPart_C_UpdateListViewItems Parms{};

	Parms.Items = std::move(Items);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.UpdatePlayerInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLegacyInventoryMenuExtraData&NewInfo                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_OriginalMenu_InventoryMainPart_C::UpdatePlayerInfo(const struct FLegacyInventoryMenuExtraData& NewInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "UpdatePlayerInfo");

	Params::WBP_OriginalMenu_InventoryMainPart_C_UpdatePlayerInfo Parms{};

	Parms.NewInfo = std::move(NewInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OriginalMenu_InventoryMainPart.WBP_OriginalMenu_InventoryMainPart_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_OriginalMenu_InventoryMainPart_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainPart_C", "BP_GetDesiredFocusTarget");

	Params::WBP_OriginalMenu_InventoryMainPart_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

