#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PairedPawnProcedureDebugInfo

#include "Basic.hpp"

#include "WBP_PairedPawnProcedureDebugInfo_classes.hpp"
#include "WBP_PairedPawnProcedureDebugInfo_parameters.hpp"


namespace SDK
{

// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.ActivateRadiusBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::ActivateRadiusBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "ActivateRadiusBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_ActivateRadiusBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.ActivateTargetNameBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::ActivateTargetNameBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "ActivateTargetNameBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_ActivateTargetNameBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PairedPawnProcedureDebugInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.ExecuteUbergraph_WBP_PairedPawnProcedureDebugInfo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PairedPawnProcedureDebugInfo_C::ExecuteUbergraph_WBP_PairedPawnProcedureDebugInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "ExecuteUbergraph_WBP_PairedPawnProcedureDebugInfo");

	Params::WBP_PairedPawnProcedureDebugInfo_C_ExecuteUbergraph_WBP_PairedPawnProcedureDebugInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.FollowDistanceBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::FollowDistanceBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "FollowDistanceBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_FollowDistanceBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.FollowTargetNameBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::FollowTargetNameBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "FollowTargetNameBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_FollowTargetNameBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.TravelAcceptanceRadiusBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::TravelAcceptanceRadiusBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "TravelAcceptanceRadiusBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_TravelAcceptanceRadiusBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.TravelTargetNameBinding
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::TravelTargetNameBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "TravelTargetNameBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_TravelTargetNameBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.UseItemTargetNameBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::UseItemTargetNameBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "UseItemTargetNameBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_UseItemTargetNameBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.UseItemUsageCountBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::UseItemUsageCountBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "UseItemUsageCountBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_UseItemUsageCountBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PairedPawnProcedureDebugInfo.WBP_PairedPawnProcedureDebugInfo_C.UseItemUsageRadiusBinding
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PairedPawnProcedureDebugInfo_C::UseItemUsageRadiusBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PairedPawnProcedureDebugInfo_C", "UseItemUsageRadiusBinding");

	Params::WBP_PairedPawnProcedureDebugInfo_C_UseItemUsageRadiusBinding Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

