#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Modern_QuestHistoryCarouselEntry

#include "Basic.hpp"

#include "WBP_Modern_QuestHistoryCarouselEntry_classes.hpp"
#include "WBP_Modern_QuestHistoryCarouselEntry_parameters.hpp"


namespace SDK
{

// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.BndEvt__WBP_Modern_QuestHistoryCarouselEntry_HitBox_K2Node_ComponentBoundEvent_1_MouseEventDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FGeometry&                 InGeometry                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             InMouseEvent                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_Modern_QuestHistoryCarouselEntry_C::BndEvt__WBP_Modern_QuestHistoryCarouselEntry_HitBox_K2Node_ComponentBoundEvent_1_MouseEventDelegate__DelegateSignature(class UUserWidget* Target, const struct FGeometry& InGeometry, const struct FPointerEvent& InMouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "BndEvt__WBP_Modern_QuestHistoryCarouselEntry_HitBox_K2Node_ComponentBoundEvent_1_MouseEventDelegate__DelegateSignature");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_BndEvt__WBP_Modern_QuestHistoryCarouselEntry_HitBox_K2Node_ComponentBoundEvent_1_MouseEventDelegate__DelegateSignature Parms{};

	Parms.Target = Target;
	Parms.InGeometry = std::move(InGeometry);
	Parms.InMouseEvent = std::move(InMouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::BP_OnItemSelectionChanged(bool bIsSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "BP_OnItemSelectionChanged");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected_0 = bIsSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Modern_QuestHistoryCarouselEntry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.ExecuteUbergraph_WBP_Modern_QuestHistoryCarouselEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::ExecuteUbergraph_WBP_Modern_QuestHistoryCarouselEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "ExecuteUbergraph_WBP_Modern_QuestHistoryCarouselEntry");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_ExecuteUbergraph_WBP_Modern_QuestHistoryCarouselEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.InpActEvt_IA_UI_Specific_QuestMenu_ScrollHistoric_K2Node_EnhancedInputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::InpActEvt_IA_UI_Specific_QuestMenu_ScrollHistoric_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "InpActEvt_IA_UI_Specific_QuestMenu_ScrollHistoric_K2Node_EnhancedInputActionEvent_0");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_InpActEvt_IA_UI_Specific_QuestMenu_ScrollHistoric_K2Node_EnhancedInputActionEvent_0 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.OnInputMethodChange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        NewInputType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::OnInputMethodChange(ECommonInputType NewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "OnInputMethodChange");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_OnInputMethodChange Parms{};

	Parms.NewInputType = NewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "OnListItemObjectSet");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "PreConstruct");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.ScrollBody
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  ScrollDelta                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::ScrollBody(double ScrollDelta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "ScrollBody");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_ScrollBody Parms{};

	Parms.ScrollDelta = ScrollDelta;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.ScrollBodyToTop
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_QuestHistoryCarouselEntry_C::ScrollBodyToTop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "ScrollBodyToTop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.UpdateBackgroundIndicator
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewBackgroundState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::UpdateBackgroundIndicator(bool NewBackgroundState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "UpdateBackgroundIndicator");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_UpdateBackgroundIndicator Parms{};

	Parms.NewBackgroundState = NewBackgroundState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.UpdateBody
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_QuestHistoryCarouselEntry_C::UpdateBody()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "UpdateBody");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.UpdateBoldness
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewIsFocus                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_QuestHistoryCarouselEntry_C::UpdateBoldness(bool NewIsFocus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "UpdateBoldness");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_UpdateBoldness Parms{};

	Parms.NewIsFocus = NewIsFocus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.UpdateDateAndYear
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_QuestHistoryCarouselEntry_C::UpdateDateAndYear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "UpdateDateAndYear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.UpdateEntry
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_QuestHistoryCarouselEntry_C::UpdateEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "UpdateEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_QuestHistoryCarouselEntry.WBP_Modern_QuestHistoryCarouselEntry_C.BP_GetDesiredFocusTarget
// (HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Modern_QuestHistoryCarouselEntry_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_QuestHistoryCarouselEntry_C", "BP_GetDesiredFocusTarget");

	Params::WBP_Modern_QuestHistoryCarouselEntry_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

