#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ModernMenu_HelpEntryMedia

#include "Basic.hpp"

#include "WBP_ModernMenu_HelpEntryMedia_classes.hpp"
#include "WBP_ModernMenu_HelpEntryMedia_parameters.hpp"


namespace SDK
{

// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.BndEvt__WBP_ModernMenu_HelpEntryMedia_BinkThumbnail_K2Node_ComponentBoundEvent_0_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    OpenedUrl                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_ModernMenu_HelpEntryMedia_C::BndEvt__WBP_ModernMenu_HelpEntryMedia_BinkThumbnail_K2Node_ComponentBoundEvent_0_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature(const class FString& OpenedUrl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "BndEvt__WBP_ModernMenu_HelpEntryMedia_BinkThumbnail_K2Node_ComponentBoundEvent_0_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature");

	Params::WBP_ModernMenu_HelpEntryMedia_C_BndEvt__WBP_ModernMenu_HelpEntryMedia_BinkThumbnail_K2Node_ComponentBoundEvent_0_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature Parms{};

	Parms.OpenedUrl = std::move(OpenedUrl);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.Close
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_HelpEntryMedia_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ModernMenu_HelpEntryMedia_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ModernMenu_HelpEntryMedia_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.ExecuteUbergraph_WBP_ModernMenu_HelpEntryMedia
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_HelpEntryMedia_C::ExecuteUbergraph_WBP_ModernMenu_HelpEntryMedia(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "ExecuteUbergraph_WBP_ModernMenu_HelpEntryMedia");

	Params::WBP_ModernMenu_HelpEntryMedia_C_ExecuteUbergraph_WBP_ModernMenu_HelpEntryMedia Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_HelpEntryMedia_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "PreConstruct");

	Params::WBP_ModernMenu_HelpEntryMedia_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.SetImage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       InTexture                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_HelpEntryMedia_C::SetImage(class UTexture2D* InTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "SetImage");

	Params::WBP_ModernMenu_HelpEntryMedia_C_SetImage Parms{};

	Parms.InTexture = InTexture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_HelpEntryMedia.WBP_ModernMenu_HelpEntryMedia_C.SetVideo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    VideoPath                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_ModernMenu_HelpEntryMedia_C::SetVideo(const class FString& VideoPath)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_HelpEntryMedia_C", "SetVideo");

	Params::WBP_ModernMenu_HelpEntryMedia_C_SetVideo Parms{};

	Parms.VideoPath = std::move(VideoPath);

	UObject::ProcessEvent(Func, &Parms);
}

}

