#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ModernHud_LevelUpGauge

#include "Basic.hpp"

#include "WBP_ModernHud_LevelUpGauge_classes.hpp"
#include "WBP_ModernHud_LevelUpGauge_parameters.hpp"


namespace SDK
{

// Function WBP_ModernHud_LevelUpGauge.WBP_ModernHud_LevelUpGauge_C.ExecuteUbergraph_WBP_ModernHud_LevelUpGauge
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernHud_LevelUpGauge_C::ExecuteUbergraph_WBP_ModernHud_LevelUpGauge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernHud_LevelUpGauge_C", "ExecuteUbergraph_WBP_ModernHud_LevelUpGauge");

	Params::WBP_ModernHud_LevelUpGauge_C_ExecuteUbergraph_WBP_ModernHud_LevelUpGauge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernHud_LevelUpGauge.WBP_ModernHud_LevelUpGauge_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernHud_LevelUpGauge_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernHud_LevelUpGauge_C", "PreConstruct");

	Params::WBP_ModernHud_LevelUpGauge_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernHud_LevelUpGauge.WBP_ModernHud_LevelUpGauge_C.SetInfoText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FModernSkillProgression&         NewSkillProgress                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ModernHud_LevelUpGauge_C::SetInfoText(struct FModernSkillProgression& NewSkillProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernHud_LevelUpGauge_C", "SetInfoText");

	Params::WBP_ModernHud_LevelUpGauge_C_SetInfoText Parms{};

	Parms.NewSkillProgress = std::move(NewSkillProgress);

	UObject::ProcessEvent(Func, &Parms);

	NewSkillProgress = std::move(Parms.NewSkillProgress);
}


// Function WBP_ModernHud_LevelUpGauge.WBP_ModernHud_LevelUpGauge_C.SetProgressValues
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FModernSkillProgression&         NewSkillProgress                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ModernHud_LevelUpGauge_C::SetProgressValues(struct FModernSkillProgression& NewSkillProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernHud_LevelUpGauge_C", "SetProgressValues");

	Params::WBP_ModernHud_LevelUpGauge_C_SetProgressValues Parms{};

	Parms.NewSkillProgress = std::move(NewSkillProgress);

	UObject::ProcessEvent(Func, &Parms);

	NewSkillProgress = std::move(Parms.NewSkillProgress);
}


// Function WBP_ModernHud_LevelUpGauge.WBP_ModernHud_LevelUpGauge_C.ToggleLevelUpIconVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernHud_LevelUpGauge_C::ToggleLevelUpIconVisibility(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernHud_LevelUpGauge_C", "ToggleLevelUpIconVisibility");

	Params::WBP_ModernHud_LevelUpGauge_C_ToggleLevelUpIconVisibility Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernHud_LevelUpGauge.WBP_ModernHud_LevelUpGauge_C.UpdateProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FModernSkillProgression&         NewSkillProgress                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ModernHud_LevelUpGauge_C::UpdateProgress(struct FModernSkillProgression& NewSkillProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernHud_LevelUpGauge_C", "UpdateProgress");

	Params::WBP_ModernHud_LevelUpGauge_C_UpdateProgress Parms{};

	Parms.NewSkillProgress = std::move(NewSkillProgress);

	UObject::ProcessEvent(Func, &Parms);

	NewSkillProgress = std::move(Parms.NewSkillProgress);
}

}

