#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ModernMenu_MagicEntry

#include "Basic.hpp"

#include "WBP_ModernMenu_MagicEntry_classes.hpp"
#include "WBP_ModernMenu_MagicEntry_parameters.hpp"


namespace SDK
{

// Function WBP_ModernMenu_MagicEntry.WBP_ModernMenu_MagicEntry_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_MagicEntry_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_MagicEntry_C", "BP_OnItemSelectionChanged");

	Params::WBP_ModernMenu_MagicEntry_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_MagicEntry.WBP_ModernMenu_MagicEntry_C.ExecuteUbergraph_WBP_ModernMenu_MagicEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_MagicEntry_C::ExecuteUbergraph_WBP_ModernMenu_MagicEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_MagicEntry_C", "ExecuteUbergraph_WBP_ModernMenu_MagicEntry");

	Params::WBP_ModernMenu_MagicEntry_C_ExecuteUbergraph_WBP_ModernMenu_MagicEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_MagicEntry.WBP_ModernMenu_MagicEntry_C.Make Brush
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UTexture2D*                       In_Texture                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FSlateBrush*                     Out_Brush                                              (Parm, OutParm)

void UWBP_ModernMenu_MagicEntry_C::Make_Brush(class UTexture2D* In_Texture, struct FSlateBrush* Out_Brush)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_MagicEntry_C", "Make Brush");

	Params::WBP_ModernMenu_MagicEntry_C_Make_Brush Parms{};

	Parms.In_Texture = In_Texture;

	UObject::ProcessEvent(Func, &Parms);

	if (Out_Brush != nullptr)
		*Out_Brush = std::move(Parms.Out_Brush);
}


// Function WBP_ModernMenu_MagicEntry.WBP_ModernMenu_MagicEntry_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_MagicEntry_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_MagicEntry_C", "OnListItemObjectSet");

	Params::WBP_ModernMenu_MagicEntry_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_MagicEntry.WBP_ModernMenu_MagicEntry_C.UpdateItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_MagicEntry_C::UpdateItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_MagicEntry_C", "UpdateItem");

	UObject::ProcessEvent(Func, nullptr);
}

}

