#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OriginalMenu_InventoryMainContent

#include "Basic.hpp"

#include "WBP_OriginalMenu_InventoryMainContent_classes.hpp"
#include "WBP_OriginalMenu_InventoryMainContent_parameters.hpp"


namespace SDK
{

// Function WBP_OriginalMenu_InventoryMainContent.WBP_OriginalMenu_InventoryMainContent_C.UpdateDescription
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      NewDescription                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    IsBackgroundDisplayed                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OriginalMenu_InventoryMainContent_C::UpdateDescription(const class FText& NewDescription, bool IsBackgroundDisplayed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OriginalMenu_InventoryMainContent_C", "UpdateDescription");

	Params::WBP_OriginalMenu_InventoryMainContent_C_UpdateDescription Parms{};

	Parms.NewDescription = std::move(NewDescription);
	Parms.IsBackgroundDisplayed = IsBackgroundDisplayed;

	UObject::ProcessEvent(Func, &Parms);
}

}

