#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OriginalMenu_InventoryMainContent

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_OriginalMenu_InventoryMainContent.WBP_OriginalMenu_InventoryMainContent_C
// 0x0010 (0x02F8 - 0x02E8)
class UWBP_OriginalMenu_InventoryMainContent_C final : public UCommonUserWidget
{
public:
	class UWBP_AltarTextBlock_C*                  inv_item_details_type;                             // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_OriginalImageTile_C*               inv_item_details_type_BG;                          // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateDescription(const class FText& NewDescription, bool IsBackgroundDisplayed);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_OriginalMenu_InventoryMainContent_C">();
	}
	static class UWBP_OriginalMenu_InventoryMainContent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_OriginalMenu_InventoryMainContent_C>();
	}
};
static_assert(alignof(UWBP_OriginalMenu_InventoryMainContent_C) == 0x000008, "Wrong alignment on UWBP_OriginalMenu_InventoryMainContent_C");
static_assert(sizeof(UWBP_OriginalMenu_InventoryMainContent_C) == 0x0002F8, "Wrong size on UWBP_OriginalMenu_InventoryMainContent_C");
static_assert(offsetof(UWBP_OriginalMenu_InventoryMainContent_C, inv_item_details_type) == 0x0002E8, "Member 'UWBP_OriginalMenu_InventoryMainContent_C::inv_item_details_type' has a wrong offset!");
static_assert(offsetof(UWBP_OriginalMenu_InventoryMainContent_C, inv_item_details_type_BG) == 0x0002F0, "Member 'UWBP_OriginalMenu_InventoryMainContent_C::inv_item_details_type_BG' has a wrong offset!");

}

