#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ModernPrefab_Notification

#include "Basic.hpp"

#include "WBP_ModernPrefab_Notification_classes.hpp"
#include "WBP_ModernPrefab_Notification_parameters.hpp"


namespace SDK
{

// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ModernPrefab_Notification_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_ModernPrefab_Notification_C::CustomEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "CustomEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.Disable Notification
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernPrefab_Notification_C::Disable_Notification()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "Disable Notification");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.Enable Notification
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernPrefab_Notification_C::Enable_Notification()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "Enable Notification");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.ExecuteUbergraph_WBP_ModernPrefab_Notification
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernPrefab_Notification_C::ExecuteUbergraph_WBP_ModernPrefab_Notification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "ExecuteUbergraph_WBP_ModernPrefab_Notification");

	Params::WBP_ModernPrefab_Notification_C_ExecuteUbergraph_WBP_ModernPrefab_Notification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.OnNotificationSetActive
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVAltarNotificationBaseWidget*    NotificationWidget                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernPrefab_Notification_C::OnNotificationSetActive(class UVAltarNotificationBaseWidget* NotificationWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "OnNotificationSetActive");

	Params::WBP_ModernPrefab_Notification_C_OnNotificationSetActive Parms{};

	Parms.NotificationWidget = NotificationWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernPrefab_Notification_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "PreConstruct");

	Params::WBP_ModernPrefab_Notification_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.Set Icon Background Visibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVisible_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernPrefab_Notification_C::Set_Icon_Background_Visibility(bool IsVisible_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "Set Icon Background Visibility");

	Params::WBP_ModernPrefab_Notification_C_Set_Icon_Background_Visibility Parms{};

	Parms.IsVisible_0 = IsVisible_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.Update Notification Visibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernPrefab_Notification_C::Update_Notification_Visibility(bool InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "Update Notification Visibility");

	Params::WBP_ModernPrefab_Notification_C_Update_Notification_Visibility Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernPrefab_Notification.WBP_ModernPrefab_Notification_C.UpdateNotification
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLegacyNotificationProperties&New_Notification                                       (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ModernPrefab_Notification_C::UpdateNotification(const struct FLegacyNotificationProperties& New_Notification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernPrefab_Notification_C", "UpdateNotification");

	Params::WBP_ModernPrefab_Notification_C_UpdateNotification Parms{};

	Parms.New_Notification = std::move(New_Notification);

	UObject::ProcessEvent(Func, &Parms);
}

}

