#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ModernMenu_Help

#include "Basic.hpp"

#include "WBP_ModernMenu_Help_classes.hpp"
#include "WBP_ModernMenu_Help_parameters.hpp"


namespace SDK
{

// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_0_OnItemClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_0_OnItemClicked__DelegateSignature(class UObject* SelectedItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_0_OnItemClicked__DelegateSignature");

	Params::WBP_ModernMenu_Help_C_BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_0_OnItemClicked__DelegateSignature Parms{};

	Parms.SelectedItem = SelectedItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_1_OnItemSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_1_OnItemSelected__DelegateSignature(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_1_OnItemSelected__DelegateSignature");

	Params::WBP_ModernMenu_Help_C_BndEvt__WBP_ModernMenu_Help_ListView_K2Node_ComponentBoundEvent_1_OnItemSelected__DelegateSignature Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BndEvt__WBP_ModernMenu_Help_NextButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::BndEvt__WBP_ModernMenu_Help_NextButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BndEvt__WBP_ModernMenu_Help_NextButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_ModernMenu_Help_C_BndEvt__WBP_ModernMenu_Help_NextButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BndEvt__WBP_ModernMenu_Help_PreviousButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::BndEvt__WBP_ModernMenu_Help_PreviousButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BndEvt__WBP_ModernMenu_Help_PreviousButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_ModernMenu_Help_C_BndEvt__WBP_ModernMenu_Help_PreviousButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BndEvt__WBP_ModernMenu_Help_ReadMoreButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::BndEvt__WBP_ModernMenu_Help_ReadMoreButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BndEvt__WBP_ModernMenu_Help_ReadMoreButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_ModernMenu_Help_C_BndEvt__WBP_ModernMenu_Help_ReadMoreButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_ModernMenu_Help_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)

void UWBP_ModernMenu_Help_C::BP_OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BP_OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BP_OnTirggeringActionCommited
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::BP_OnTirggeringActionCommited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BP_OnTirggeringActionCommited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.CanDoOneMoreStep
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Forward                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_ModernMenu_Help_C::CanDoOneMoreStep(bool Forward)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "CanDoOneMoreStep");

	Params::WBP_ModernMenu_Help_C_CanDoOneMoreStep Parms{};

	Parms.Forward = Forward;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ModernMenu_Help_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.DoScroll
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  ScrollDeltaRaw                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVModernScrollBox*                ScrollBoxTarget                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::DoScroll(double ScrollDeltaRaw, class UVModernScrollBox* ScrollBoxTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "DoScroll");

	Params::WBP_ModernMenu_Help_C_DoScroll Parms{};

	Parms.ScrollDeltaRaw = ScrollDeltaRaw;
	Parms.ScrollBoxTarget = ScrollBoxTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.ExecuteUbergraph_WBP_ModernMenu_Help
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::ExecuteUbergraph_WBP_ModernMenu_Help(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "ExecuteUbergraph_WBP_ModernMenu_Help");

	Params::WBP_ModernMenu_Help_C_ExecuteUbergraph_WBP_ModernMenu_Help Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.FadeInOutMenu
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsVisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromLeft                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInstant                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::FadeInOutMenu(bool bIsVisible, bool bFromLeft, bool bInstant)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "FadeInOutMenu");

	Params::WBP_ModernMenu_Help_C_FadeInOutMenu Parms{};

	Parms.bIsVisible = bIsVisible;
	Parms.bFromLeft = bFromLeft;
	Parms.bInstant = bInstant;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.Handle Input Scrolling
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  In_Scroll_Delta_Raw                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::Handle_Input_Scrolling(double In_Scroll_Delta_Raw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "Handle Input Scrolling");

	Params::WBP_ModernMenu_Help_C_Handle_Input_Scrolling Parms{};

	Parms.In_Scroll_Delta_Raw = In_Scroll_Delta_Raw;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.HandleSectionWhenNavigatingFromDetailsPanel
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Forward                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::HandleSectionWhenNavigatingFromDetailsPanel(bool Forward)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "HandleSectionWhenNavigatingFromDetailsPanel");

	Params::WBP_ModernMenu_Help_C_HandleSectionWhenNavigatingFromDetailsPanel Parms{};

	Parms.Forward = Forward;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.InitializeDetails
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::InitializeDetails()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "InitializeDetails");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.InpActEvt_IA_UI_Generic_NavigateDown_K2Node_EnhancedInputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::InpActEvt_IA_UI_Generic_NavigateDown_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "InpActEvt_IA_UI_Generic_NavigateDown_K2Node_EnhancedInputActionEvent_0");

	Params::WBP_ModernMenu_Help_C_InpActEvt_IA_UI_Generic_NavigateDown_K2Node_EnhancedInputActionEvent_0 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.InpActEvt_IA_UI_Generic_NavigateUp_K2Node_EnhancedInputActionEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::InpActEvt_IA_UI_Generic_NavigateUp_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "InpActEvt_IA_UI_Generic_NavigateUp_K2Node_EnhancedInputActionEvent_1");

	Params::WBP_ModernMenu_Help_C_InpActEvt_IA_UI_Generic_NavigateUp_K2Node_EnhancedInputActionEvent_1 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.InpActEvt_IA_UI_Specific_HelpMenu_More_K2Node_EnhancedInputActionEvent_3
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::InpActEvt_IA_UI_Specific_HelpMenu_More_K2Node_EnhancedInputActionEvent_3(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "InpActEvt_IA_UI_Specific_HelpMenu_More_K2Node_EnhancedInputActionEvent_3");

	Params::WBP_ModernMenu_Help_C_InpActEvt_IA_UI_Specific_HelpMenu_More_K2Node_EnhancedInputActionEvent_3 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.InpActEvt_IA_UI_Specific_HelpMenu_Prev_K2Node_EnhancedInputActionEvent_4
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::InpActEvt_IA_UI_Specific_HelpMenu_Prev_K2Node_EnhancedInputActionEvent_4(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "InpActEvt_IA_UI_Specific_HelpMenu_Prev_K2Node_EnhancedInputActionEvent_4");

	Params::WBP_ModernMenu_Help_C_InpActEvt_IA_UI_Specific_HelpMenu_Prev_K2Node_EnhancedInputActionEvent_4 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.InpActEvt_IA_UI_Specific_HelpMenu_ScrollDetails_K2Node_EnhancedInputActionEvent_2
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::InpActEvt_IA_UI_Specific_HelpMenu_ScrollDetails_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "InpActEvt_IA_UI_Specific_HelpMenu_ScrollDetails_K2Node_EnhancedInputActionEvent_2");

	Params::WBP_ModernMenu_Help_C_InpActEvt_IA_UI_Specific_HelpMenu_ScrollDetails_K2Node_EnhancedInputActionEvent_2 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.LoadHelpMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::LoadHelpMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "LoadHelpMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.MenuFadeInOut
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIsVisible                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InIsFromLeft                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InInstant                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::MenuFadeInOut(bool InIsVisible, bool InIsFromLeft, bool InInstant)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "MenuFadeInOut");

	Params::WBP_ModernMenu_Help_C_MenuFadeInOut Parms{};

	Parms.InIsVisible = InIsVisible;
	Parms.InIsFromLeft = InIsFromLeft;
	Parms.InInstant = InInstant;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.NavigateEntryFromMoreDetailsPanel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Forward                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   DidOneStep                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::NavigateEntryFromMoreDetailsPanel(bool Forward, bool* DidOneStep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "NavigateEntryFromMoreDetailsPanel");

	Params::WBP_ModernMenu_Help_C_NavigateEntryFromMoreDetailsPanel Parms{};

	Parms.Forward = Forward;

	UObject::ProcessEvent(Func, &Parms);

	if (DidOneStep != nullptr)
		*DidOneStep = Parms.DidOneStep;
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.NavigateToNextOrPrevEntryInList
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Forward                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::NavigateToNextOrPrevEntryInList(bool Forward)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "NavigateToNextOrPrevEntryInList");

	Params::WBP_ModernMenu_Help_C_NavigateToNextOrPrevEntryInList Parms{};

	Parms.Forward = Forward;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.On Input Method Changed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        bNewInputType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::On_Input_Method_Changed(ECommonInputType bNewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "On Input Method Changed");

	Params::WBP_ModernMenu_Help_C_On_Input_Method_Changed Parms{};

	Parms.bNewInputType = bNewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.OnDataSelectionToggled
// (Event, Public, BlueprintEvent)

void UWBP_ModernMenu_Help_C::OnDataSelectionToggled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "OnDataSelectionToggled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.OnFocus
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::OnFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "OnFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.OnListEntriesUpdated
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class UHelpMenuListEntryData*>&InListData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ModernMenu_Help_C::OnListEntriesUpdated(const TArray<class UHelpMenuListEntryData*>& InListData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "OnListEntriesUpdated");

	Params::WBP_ModernMenu_Help_C_OnListEntriesUpdated Parms{};

	Parms.InListData = std::move(InListData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.OnNavigateEntry
// (Event, Public, BlueprintEvent)
// Parameters:
// class UHelpMenuListEntryData*           Entry                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::OnNavigateEntry(class UHelpMenuListEntryData* Entry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "OnNavigateEntry");

	Params::WBP_ModernMenu_Help_C_OnNavigateEntry Parms{};

	Parms.Entry = Entry;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.PopulateListDetail
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::PopulateListDetail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "PopulateListDetail");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.SetInputForFooter
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_Modern_Menu_Player_Footer_C* Footer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::SetInputForFooter(class UWBP_Modern_Menu_Player_Footer_C* Footer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "SetInputForFooter");

	Params::WBP_ModernMenu_Help_C_SetInputForFooter Parms{};

	Parms.Footer = Footer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.Show More
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::Show_More()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "Show More");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.ShowLess
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_ModernMenu_Help_C::ShowLess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "ShowLess");

	Params::WBP_ModernMenu_Help_C_ShowLess Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.UnloadHelpMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::UnloadHelpMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "UnloadHelpMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.UpdateFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ModernMenu_Help_C::UpdateFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "UpdateFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.UpdateFooter
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UHelpMenuListEntryData*           SelectedEntry                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::UpdateFooter(class UHelpMenuListEntryData* SelectedEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "UpdateFooter");

	Params::WBP_ModernMenu_Help_C_UpdateFooter Parms{};

	Parms.SelectedEntry = SelectedEntry;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.UpdateListEntryAnimation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UObject*                    Item                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::UpdateListEntryAnimation(const class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "UpdateListEntryAnimation");

	Params::WBP_ModernMenu_Help_C_UpdateListEntryAnimation Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.UpdateListEntryAnimationInstant
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UObject*                    Item                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::UpdateListEntryAnimationInstant(const class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "UpdateListEntryAnimationInstant");

	Params::WBP_ModernMenu_Help_C_UpdateListEntryAnimationInstant Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.UpdateViewMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ModernMenu_Help_C::UpdateViewMode(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "UpdateViewMode");

	Params::WBP_ModernMenu_Help_C_UpdateViewMode Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ModernMenu_Help.WBP_ModernMenu_Help_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_ModernMenu_Help_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ModernMenu_Help_C", "BP_GetDesiredFocusTarget");

	Params::WBP_ModernMenu_Help_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

