#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OriginalMenu_Inventory_FilterScrollbox

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_OriginalMenu_Inventory_FilterScrollbox.WBP_OriginalMenu_Inventory_FilterScrollbox_C
// 0x0000 (0x0508 - 0x0508)
class UWBP_OriginalMenu_Inventory_FilterScrollbox_C final : public UVAltarNavigableScrollBox
{
public:
	void SetFocusedElement(int32 ElementID);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_OriginalMenu_Inventory_FilterScrollbox_C">();
	}
	static class UWBP_OriginalMenu_Inventory_FilterScrollbox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_OriginalMenu_Inventory_FilterScrollbox_C>();
	}
};
static_assert(alignof(UWBP_OriginalMenu_Inventory_FilterScrollbox_C) == 0x000008, "Wrong alignment on UWBP_OriginalMenu_Inventory_FilterScrollbox_C");
static_assert(sizeof(UWBP_OriginalMenu_Inventory_FilterScrollbox_C) == 0x000508, "Wrong size on UWBP_OriginalMenu_Inventory_FilterScrollbox_C");

}

